version: "3.7"

services:
  app-frontend:
    build: .
    container_name: meufretecom-frontend
    # ports:
    #   - 3000:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/app-frontend:delegated
    network_mode: host
    

volumes:
  pgdata:
    driver: local