version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_meufretecom
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=omodei
      - POSTGRES_DB=meufretecom
    volumes:
      - pgdata:/data/postgres
    network_mode: host
 
  app:
    build: .
    container_name: meufretecom
    # ports:
    #   - 3334:3334
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local